# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  packer_valid:
    runs-on: ubuntu-18.04
    container:
      image: hashicorp/packer
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: packer validation
        run: |+
          packer validate \
          -var vc_vcenter_IP=192.168.1.1 \
          -var vc_password=test \
          -var vc_vm_name=test \
          -var vc_esxi_host=test \
          centos8/centos8.2.json
