name: Packer_Template_Validation

on: [push, pull_request]

jobs:
  packer_inspection:
    runs-on: ubuntu-18.04
    container:
      image: hashicorp/packer
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: packer inspect
        run: |+
          packer inspect \
          centos8/centos8.2.json
  packer_validate:
    runs-on: ubuntu-18.04
    container:
      image: hashicorp/packer
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: packer config validation
        run: |+
          packer validate \
          -var vc_vcenter_IP=192.168.1.1 \
          -var vc_password=test \
          -var vc_vm_name=test \
          -var vc_esxi_host=test \
          -var vc_vmname=test \
          -var iso_checksum_type=sha256 \
          centos8/centos8.2.json
      - name: packer config normalized check
        run: |+
          packer fix  centos8/centos8.2.json |\
          diff - centos8/centos8.2.json
