# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  packer_valid:
    runs-on: ubuntu-18.04
    container:
      image: hashicorp/packer
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: pwd
        run: pwd
      - name: ls
        run: ls -RF
      - name: packer validation
        run: |+
          packer validate \
          -var vcenter_server=test \
          -var password=test \
          -var vm_name=test \
          -var host=test \
          centos8/centos8.2.json
